name: preprod-bo-server

on:
  push:
    branches:
      - "master"
    paths:
      - "apps/bo-server/**"
      - "packages/freely-prisma/**"
      - "packages/tsconfig/**"
      - ".github/workflows/preprod-bo-server.yml"

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx turbo run build --filter=bo-server...

      - name: Test
        run: npx turbo run test --filter=bo-server...

      - name: prisma migrate deploy
        run: npx prisma migrate deploy --schema ./packages/freely-prisma/schema.prisma

      - name: Deploy server to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ced-bo-server-preprod"
          heroku_email: "cedric.nicoloso@gmail.com"
